export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const GET_LOCATION = "GET_LOCATION"
export const GET_LOCATION_BY_ID = "GET_LOCATION_BY_ID"
export const GET_PASIEN = "GET_PASIEN"
export const GET_PASIEN_BY_ID = "GET_PASIEN_BY_ID"
export const GET_PASIEN_BY_ID_KEL = "GET_PASIEN_BY_ID_KEL"